# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: blog_ds
theme:
  name: material
  #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  features:
    - navigation.expand
    - tabs
markdown_extensions:
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break
  - toc:
      permalink: '#' # heading anchor
  - admonition
  - pymdownx.highlight: # 9.x 替换旧 codehilite（代码高亮）
      guess_lang: false
  - pymdownx.superfences # 围栏代码块 + 高亮
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  #- pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - roamlinks
    #- autolinks
  - exclude:
      glob:
        - "**/.DS_Store"
        - "**/*.tmp"
        - "**/*.pdf"
        - "**/*.ppt"
        - "**/*.pptx"
        - "**/*.doc"
        - "**/*.docx"
        - "**/*.xls"
        - "**/*.xlsx"
        - "**/*.csv"
        - "**/*.gz"
        - "08_业务专题/Digital_retail/**"
        - "09_语言篇/R/1. Data science course/**"
        - "07_语言篇/R/1. Data science course/**"
      regex:
        - '.*\.(tmp|bin|tar|db|sqlite|pem|key|p12)$'

extra_javascript:
    - 'js/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  # extra_javascript:
  # - javascripts/mathjax.js6283897707209

  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
